/******************************************************************
 * This code was generated by the Astade CppGenerator.            *
 * The generated code is not per se a derivative work of Astade;  *
 * the original copyright to this code is held by the holder(s)   *
 * of the copyright to the underlying model at the time this code *
 * was generated; this code may be distributed under terms of     *
 * his/her/their choice.                                          */
/** an import
 *  @file CImport.cpp
 ******************************************************************/

#include "CImport.h"	 // own header



//****** Trace Macros ***************
#ifndef NOTIFY_CONSTRUCTOR
#  define NOTIFY_CONSTRUCTOR(a,b,c)
#endif
#ifndef NOTIFY_DESTRUCTOR
#  define NOTIFY_DESTRUCTOR(a,b)
#endif
#ifndef NOTIFY_FUNCTION_CALL
#  define NOTIFY_FUNCTION_CALL(a,b,c,d,e,f)
#endif
#ifndef NOTIFY_RETURN_VALUE
#  define NOTIFY_RETURN_VALUE(a)
#endif
#ifndef RETURN
#  define RETURN(a) return(a)
#endif

#ifndef LOG
#  define LOG(...)
#endif

doxyqml::CImport::CImport(const std::string& importLine) :
	m_ImportLineText(importLine)
{
	NOTIFY_CONSTRUCTOR(5, "CImport", "const std::string& importLine")
//[Package_doxyqml/Package_ast/classes/class_CImport/operations/constructor/code.cpp]
	//~~ CRootElement(const std::string& filename) [CRootElement] ~~
//[EOF]
}

void doxyqml::CImport::print() const
{
	NOTIFY_FUNCTION_CALL(this, 5, "CImport", "print", "", "void ")
//[Package_doxyqml/Package_ast/classes/class_CImport/operations/operation_print/code.cpp]
	//~~ void print() [CImport] ~~
	printf("// import%s\n",m_ImportLineText.c_str());
//[EOF]
}

