/******************************************************************
 * This code was generated by the Astade CppGenerator.            *
 * The generated code is not per se a derivative work of Astade;  *
 * the original copyright to this code is held by the holder(s)   *
 * of the copyright to the underlying model at the time this code *
 * was generated; this code may be distributed under terms of     *
 * his/her/their choice.                                          */
/** an import
 *  @file CImport.h
 ******************************************************************/

#ifndef __CIMPORT_H
#  define __CIMPORT_H

//****** specification prolog ******
//[Package_doxyqml/Package_ast/classes/class_CImport/prolog.h]
#include <string>
//[EOF]
//**********************************

// Relation includes:
#include "CQmlObject.h"


/** all doxyqml dependend classes
*/
namespace doxyqml {
/** an import
*/
class CImport : public CQmlObject
{

public:
/** construct from a text
@param importLine the text of the element
*/
	CImport(const std::string& importLine);

/** print the generated code to stdout
*/
	virtual void print() const;


protected:

private:
/** the text of the import line
*/
	std::string	m_ImportLineText;

};
} // namespace doxyqml

#endif
