/******************************************************************
 * This code was generated by the Astade CppGenerator.            *
 * The generated code is not per se a derivative work of Astade;  *
 * the original copyright to this code is held by the holder(s)   *
 * of the copyright to the underlying model at the time this code *
 * was generated; this code may be distributed under terms of     *
 * his/her/their choice.                                          */
/** an import with namespace
 *  @file CNamespaceImport.h
 ******************************************************************/

#ifndef __CNAMESPACEIMPORT_H
#  define __CNAMESPACEIMPORT_H

//****** specification prolog ******
//[Package_doxyqml/Package_ast/classes/class_YMCKDJUQ/prolog.h]
#include <string>
//[EOF]
//**********************************

// Relation includes:
#include "CQmlObject.h"


/** all doxyqml dependend classes
*/
namespace doxyqml {
/** an import with namespace
*/
class CNamespaceImport : public CQmlObject
{

public:
/** construct from a text
@param filename the text of the element
@param namespaceName the text of the element
*/
	CNamespaceImport(const std::string& filename, const std::string& namespaceName);

/** print the generated code to stdout
*/
	virtual void print() const;


protected:

private:
/** the text of the import line
*/
	std::string	m_filename;

/** the text of the import line
*/
	std::string	m_NamespaceName;

};
} // namespace doxyqml

#endif
