/******************************************************************
 * This code was generated by the Astade CppGenerator.            *
 * The generated code is not per se a derivative work of Astade;  *
 * the original copyright to this code is held by the holder(s)   *
 * of the copyright to the underlying model at the time this code *
 * was generated; this code may be distributed under terms of     *
 * his/her/their choice.                                          */
/** a single line comment
 *  @file CSinglelineComment.h
 ******************************************************************/

#ifndef __CSINGLELINECOMMENT_H
#  define __CSINGLELINECOMMENT_H

//****** specification prolog ******
//[Package_doxyqml/Package_ast/classes/class_CSinglelineComment/prolog.h]
#include <string>
//[EOF]
//**********************************

// Relation includes:
#include "CQmlObject.h"


/** all doxyqml dependend classes
*/
namespace doxyqml {
/** a single line comment
*/
class CSinglelineComment : public CQmlObject
{

public:
/** construct from a text
@param comment the text of the element
*/
	CSinglelineComment(const std::string& comment);

/** print the generated code to stdout
*/
	virtual void print() const;


protected:

private:
/** the text of the comment
*/
	std::string	m_CommentText;

};
} // namespace doxyqml

#endif
